markdown: redcarpet
highlighter: pygments
permalink: pretty
title: 'My worklog'
tagline: 'My worklog'
description: 'My worklog'
url: warfish.github.io
baseurl: /

author:
    name: 'Evgeny Yakovlev'
    url:  warfish.github.io

paginate: 10

github:
    repo: https://github.com/warfish/warfish.github.io

