markdown: redcarpet
highlighter: pygments
permalink: pretty
title: 'My worklog'
tagline: 'My worklog'
description: 'My worklog'
url: warfish.github.io
baseurl: /

images_root: '/public/images'

tag_page_layout: tag_page
tag_page_dir: .

author:
    name: 'Evgeny Yakovlev'
    url:  warfish.github.io

paginate: 10

github:
    repo: https://github.com/warfish/warfish.github.io

